### ISSUE TITLE
Ever heard of promises?

### ISSUE THREAD

**Issue by steelbrain** [frank-dspeed/demo-nodejs-module-fail#1]
The title says it all

**Comment by frank-dspeed** [comment]
not heard about it but sounds promissing lol :dash:

**Comment by steelbrain** [comment]
Hahaha.
It's the new big thing.
```js
SSH.connect().then(function(Connection){
  Connection.exec('doSomething').then(JSON.parse).then(function(DecodedResults){
    console.log(DecodedResults)
  });
});
```

**Comment by steelbrain** [comment]
That was a real life example of https://github.com/steelbrain/node-ssh

**Comment by steelbrain** [comment]
Gonna close it as it makes no sense to keep it opened.

**Comment by frank-dspeed** [comment]
ya right makes no sense i like the promis idea and this Q but it will take a lot of time to get it working and fully understand it i tought i understood the basics but don't got goood results at presents a call back is working but will look forward to implament promises in future some how thx a lot

**Comment by steelbrain** [comment]
Note: Promises have been natively implemented since Chrome v42, or if you want a lightweight alternative to Q, try my `a-promise` repo

**Comment by frank-dspeed** [comment]
looks good to but the main problem i have with promises at present are the values and that need to get behind the thinking and how to use the fullfill array and the results and all that.
